# Generated by Django 4.1.7 on 2023-02-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plans',
            old_name='title',
            new_name='titulo',
        ),
    ]
